global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: "smollm2-blue"
    static_configs:
      - targets: ["smollm2-blue:8000"]
        labels:
          color: "blue"
          service: "model-server"
    metrics_path: "/metrics"

  - job_name: "smollm2-green"
    static_configs:
      - targets: ["smollm2-green:8000"]
        labels:
          color: "green"
          service: "model-server"
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
